### ISSUE TITLE
Unable to create alarm in aodh alrming service using openstack4j

### ISSUE THREAD

**Issue by zhangjianweibj** [ContainX/openstack4j#896] opened 2016-11-25 08:16 UTC
![image](https://cloud.githubusercontent.com/assets/18585129/20618519/781d57e8-b32a-11e6-845d-a882a4d3ec6a.png)
 
openstack-n,create alarm,the request is sent to 8777 port, which is telemetry metering service. in fact it should be sent to 8042 port, where the telemetry alarming service is running.

**Comment by zhangjianweibj** [comment] 2016-11-25 08:20
![image](https://cloud.githubusercontent.com/assets/18585129/20618607/10763c6c-b32b-11e6-8a6e-da62b2fc46a8.png)

**Comment by auhlig** [comment] 2016-12-23 11:58
PR merged. Please close if the issue is fixed @zhangjianweibj.

**Closed** 2016-12-23 12:28 UTC
Labels: enhancement
