### ISSUE TITLE
getConsoleOutput() throw exception

### ISSUE THREAD

**Issue by gwhhub** [ContainX/openstack4j#906] opened 2016-12-26 03:39 UTC
`os.compute().servers().getConsoleOutput("8ddc300b-8c1c-413f-8d3d-e4cab5570767", 2)`
throw exception 
Exception in thread "main" ConnectionException{message=could not find writer for content-type application/json type: java.lang.String, status=0}
	at org.openstack4j.connectors.resteasy.HttpExecutorServiceImpl.invoke(HttpExecutorServiceImpl.java:56)
	at org.openstack4j.connectors.resteasy.HttpExecutorServiceImpl.execute(HttpExecutorServiceImpl.java:30)
	at org.openstack4j.core.transport.internal.HttpExecutor.execute(HttpExecutor.java:51)
	at org.openstack4j.openstack.internal.BaseOpenStackService$Invocation.execute(BaseOpenStackService.java:208)
	at org.openstack4j.openstack.internal.BaseOpenStackService$Invocation.execute(BaseOpenStackService.java:202)
	at org.openstack4j.openstack.compute.internal.ServerServiceImpl.getConsoleOutput(ServerServiceImpl.java:266)
	at test.testV22.main(testV22.java:120)
Caused by: java.lang.RuntimeException: could not find writer for content-type application/json type: java.lang.String
	at org.jboss.resteasy.client.ClientRequest.writeRequestBody(ClientRequest.java:470)
	at org.jboss.resteasy.client.core.executors.ApacheHttpClient4Executor.writeRequestBodyToOutputStream(ApacheHttpClient4Executor.java:393)
	at org.jboss.resteasy.client.core.executors.ApacheHttpClient4Executor.buildEntity(ApacheHttpClient4Executor.java:360)
	at org.jboss.resteasy.client.core.executors.ApacheHttpClient4Executor.loadHttpMethod(ApacheHttpClient4Executor.java:332)
	at org.jboss.resteasy.client.core.executors.ApacheHttpClient4Executor.execute(ApacheHttpClient4Executor.java:180)
	at org.jboss.resteasy.client.ClientRequest.execute(ClientRequest.java:438)
	at org.jboss.resteasy.client.ClientRequest.httpMethod(ClientRequest.java:688)
	at org.jboss.resteasy.client.ClientRequest.httpMethod(ClientRequest.java:694)
	at org.openstack4j.connectors.resteasy.HttpCommand.execute(HttpCommand.java:65)
	at org.openstack4j.connectors.resteasy.HttpExecutorServiceImpl.invokeRequest(HttpExecutorServiceImpl.java:61)
	at org.openstack4j.connectors.resteasy.HttpExecutorServiceImpl.invoke(HttpExecutorServiceImpl.java:54)
	... 6 more

**Comment by df101** [comment] 2016-12-26 03:55
I also meet the same problem@auhlig

**Comment by fitcoderyoung** [comment] 2016-12-26 03:56
I've had this problem too,please solve it as soon as possible!

**Comment by auhlig** [comment] 2016-12-26 10:29
Hi guys,
I'm aware of this.
Worth trying a different connector for now.

**Comment by auhlig** [comment] 2016-12-26 16:13
Is someone, who is able to reproduce the error, volunteering to look into this? Maybe it's matter of maven dependencies. Would be much appreciated. @gwhhub @df101 @fitcoderyoung

**Comment by auhlig** [comment] 2016-12-27 12:02
Duplicate of #795. Closing.

**Closed by auhlig** 2016-12-27 12:02 UTC
