### ISSUE TITLE
KeystoneAuth does not have a default constructor

### ISSUE THREAD

**Issue by whaon** [ContainX/openstack4j#838] opened 2016-09-30 01:55 UTC
this may cause problems when using jackson to handle it

**Comment by auhlig** [comment] 2016-09-30 06:09
Can you share more details?

**Comment by whaon** [comment] 2016-10-08 08:32
```
public KeystoneAuth(String tokenId, AuthScope scope) {
        this.identity = AuthIdentity.createTokenType(tokenId);
        this.scope = scope;
        this.type = Type.TOKEN;
    }

    public KeystoneAuth(String userId, String password) {
        this(userId, password, null, null);
    }

    public KeystoneAuth(String user, String password, Identifier domain, AuthScope scope) {
        this.identity = AuthIdentity.createCredentialType(user, password, domain);
        this.scope = scope;
        this.type = Type.CREDENTIALS;
    }

    protected KeystoneAuth(Type type) {
        this.type = type;
    }
```

as we see above,there is no constructor with no parameters in the KeystoneAuth class.
this may cause some problems when using jackson to handle  it

**Comment by auhlig** [comment] 2016-10-08 09:52
So far I'm not aware this caused problems and tests are passing. Did you experience any errors caused by this?

**Comment by whaon** [comment] 2016-10-09 02:00
Oh,sorry, I have forgot to say that it's OK to serialize it but faild when deserialize it if the Classs does not have a default empty params constructor,the exception occurs like the below:
```
com.fasterxml.jackson.databind.JsonMappingException: No suitable constructor found for type [simple type, class com.xxx.A]: can not instantiate from JSON object (missing default constructor or creator, or perhaps need to add/enable type information?)
```

**Comment by auhlig** [comment] 2016-10-10 21:04
Ah. Okay. Thanks for explaining. Would you like to submit a PR for that?

**Comment by whaon** [comment] 2016-10-12 01:55
see pr:[848](https://github.com/ContainX/openstack4j/pull/848)

**Comment by auhlig** [comment] 2016-10-12 09:05
Just merged the PR. Cam we close this issue @whaon ?

**Closed** 2016-10-12 09:23 UTC
Labels: bug, PR Merged
