### ISSUE TITLE
Can only hold one OSClient in memory at a time

### ISSUE THREAD

**Issue by n-r-anderson** [ContainX/openstack4j#339] opened 2015-04-22 18:19 UTC
On latest master as of 4/16/2015...

I have a routine that copies an image from one OS controller (source) to another (destination).  Found that I could instantiate multiple OSClient instances which are distinct objects, but underlying services/URLs still point to the last created OSClient.  I have not examined the source code or run a multi-threaded test, but I'm guessing the OSClients point to statics/singletons? 

Found work-around, please add to knowledge base until/unless issue fixed.

Code sample with work-around notes below:
----------------------------------------------------------
OSClient sourceOs = OSFactory.clientFromAccess(access1);
OSClient destinationOs = OSFactory.clientFromAccess(access2);

List<Image> images =  (List<Image>) destination.images().listAll();
// Do some processing to check if image exists, etc.

// oops if I don't re-initialize the sourceOs, these calls will get issued vs. destination URL
sourceOs = OSFactory.clientFromAccess(access1);
Image image = sourceOs.images().get(imageId);
InputStream input = sourceOs.images().getAsStream(imageId);

// oops, again, need to re-initialize destinationOs or calls will execute vs. source URL
destinationOs = OSFactory.clientFromAccess(access2);
Image copy = destinationOs.images().reserve(Builders.image().name(image.getName()).isPublic(true).build());

copy = destinationOs.images().upload(copy.getId(), Payloads.create(input), copy.toBuilder().containerFormat(image.getContainerFormat()).diskFormat(image.getDiskFormat().build());

**Comment by symcssn** [comment] 2015-04-22 18:59
The underlying session object is stored inside a thread local. It is designed so that a thread can only have one session object.  This behavior is expected.

**Comment by gondor** [comment] 2015-04-22 22:21
Thank you @symcssn for providing an answer.  This is correct and intended behavior.  Most use cases by the community are a single endpoint per thread.  In a multi-threaded application we provide the fromAccess() call so you can retain access with say a session scope and retrieve it on the new thread, etc.

The API has been greatly tied around the original thread-local approach since day 1 so any service can grab info at any point without passing around a boilerplate object.

**Comment by vinodborole** [comment] 2016-08-22 09:23
@n-r-anderson closing this issue for now, please reopen it if you feel its still an issue

**Closed by vinodborole** 2016-08-22 09:23 UTC
