### ISSUE TITLE
Route missing external_fixed_ips

### ISSUE THREAD

**Issue by z839978721** [ContainX/openstack4j#1042] opened 2017-06-08 06:39 UTC
openstack api:
-
"external_gateway_info": {
                "enable_snat": true,
                "external_fixed_ips": [
                    {
                        "ip_address": "172.24.4.3",
                        "subnet_id": "b930d7f6-ceb7-40a0-8b81-a425dd994ccf"
                    },
                    {
                        "ip_address": "2001:db8::c",
                        "subnet_id": "0c56df5d-ace5-46c8-8f4c-45fa4e334d18"
                    }
                ],
                "network_id": "ae34051f-aa6c-4c75-abf5-50dc9ac99ef3"
            }

openstack4j api:
-
public interface ExternalGateway extends ModelEntity {

	/**
	 * @return the network identifier
	 */
	String getNetworkId();
	
	/**
	 * SNAT can be enabled or disabled at any time on a Neutron router regardless of the current status of floating IPs. 
	 * Floating IPs will continue working even when SNAT is disabled. 
	 * 
	 * NOTE: The default setting is True to ensure backward compatibility for plugins supporting this extension.
	 * 
	 * @return true if SNAT is enabled
	 */
	boolean isEnableSnat();
	
}

Route missing external_fixed_ips

**Comment by auhlig** [comment] 2017-06-08 06:48
Duplicate of #1041

**Closed by auhlig** 2017-06-08 06:48 UTC
